config/routes.rb
Rails.application.routes.draw do
    
    resources :reports
    resources :site_masters
    scope module: :backoffice do
        get 'console/setting_planet(/:fandom_id)',  to: 'console#setting_planet'
        post 'console/save_planet_information',     to: 'console#save_planet_information'
        post 'console/save_planet_wiki',            to: 'console#save_planet_wiki'
        post 'console/add_subwiki',                 to: 'console#add_subwiki'
        get 'console/delete_subwiki/:id',           to: 'console#delete_subwiki'
        post 'console/create_wiki_info',            to: 'console#create_wiki_info'
        post 'console/update_wiki_info/:id',        to: 'console#update_wiki_info'
        post 'console/delete_wiki_info/:id',        to: 'console#delete_wiki_info'
        
        get 'console/admin'
    
        get 'console/site_config'
    
        get 'console/debug'
    end

    ## User
    devise_for :users, :controllers => {
            sessions: 'users/sessions',
            registrations: 'users/registrations',
            confirmations: 'users/confirmations',
            passwords: 'users/passwords',
            omniauth_callbacks: 'users/omniauth_callbacks'
    }
    get 'u/d', to: 'home#destroy2', as: 'user_inactivate'

    resources :myfandoms

    resources :links
    resources :fandoms do
        scope module: :planet do
            resources :wikis
            resources :histories
            resources :schedules

            resources :wiki_posts
        end
    end

    scope module: :action do
        resources :likes, path: '/action/likes'
        resources :clips, path: '/action/clips'
    end

    root 'home#go_for'
    
    # query
    # > sort by : watched, clip, maum
    get '/sort_by/:req', to: 'home#sort_by'
    
    # > load card(무한 스크롤)
    get '/load_card/:page_num', to: 'home#load_card'
    
    # > filter by : all, image, video, others
    get '/filter_by', to: 'home#filter_by'

    # home
    # > my
    get 'home/index', to: 'home#index', as: 'home_my'

    # > new
    get 'home/new', to: 'home#new_content', as: 'home_new'

    # my page
    # > my channels
    get 'mypage/my_channels', as: 'mypage_my_channels'

    # > contributed
    get 'mypage/contributed', as: 'mypage_contributed'

    # > watched
    get 'mypage/watched', as: 'mypage_watched'

    # Utility
    # > wiki post Img uploader
    post '/summernote_imageUpload', to: 'hf_util#wiki_image_uploader'
    
    # > url crawler
    post '/crawler/uri_spy', to: 'home#uri_spy', as: 'crawling_uri'

    # > link visiting counter
    post '/utils/user_watched_this_link', to: 'home#visited_link_counter', as: 'visited_link_counter'

    # > letter_counter
    get '/letter_counter', to: 'home#letter_count'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    # Admin Dashboard
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    # Error Page
    %w( 404 422 500 ).each do |code|
        get "/#{code}", to: 'errors#show', code: code
    end

    # Debug
    match 'hf_util/user_must_have_unique_myfandom/:id', to: 'hf_util#user_must_have_unique_myfandom', via: [:get]
    match 'hf_util/history/dummy/:to_do', to: 'hf_util#dummy_push', via: [:get]
end

app/controllers/home_controller.rb
require 'nokogiri'
require 'open-uri'
require 'open_uri_redirections'

class HomeController < ApplicationController
    before_action :filling_tab_group, only: [:index, :new_content]
    before_action :my_published_fandoms

    def go_for
        if user_signed_in?
            if current_user.fandoms.published.count.zero?
                redirect_to home_my_path
            else
                redirect_to home_my_path
            end
        else
            redirect_to home_new_path
        end
    end

    def new_content
        @tabs[0][:active] = 'active'
        @links = []
        @links = Link.at_home_display
        @fandoms = current_user.fandoms.published if user_signed_in?
    end

    def index
        @tabs[1][:active] = 'active'
        @links = []
        @links = current_user.fandoms.links_all_at_homeMy if user_signed_in?
        @fandoms = current_user.fandoms.published if user_signed_in?
    end

    # GET /u/d
    def destroy2
        if current_user.update(active: false)
            puts "\tDestroy Session! and Active Falsed!"
            redirect_to destroy_user_session_path
        else
            redirect_to :back
        end
    end
    
    
    
    # GET '/sort_by/:req' :: params[:req] == 'watched' or 'clip' or 'maum'
    def sort_by
        @req    = params[:req] || 'watched'
        
        limit   = 30
        limit   = params[:cards_limit]    if params[:cards_limit]
        
        page    = 1
        page    = params[:page]           if params[:page]
        
        bridge  = []

        puts "\n\n\n"
        puts "limit: #{limit}"
        puts "page: #{page}"
        puts "\n\n\n\n"
        
        case @req
        when 'watched'
            bridge = current_user.visited_links.order(updated_at: :desc).limit(limit).offset(limit * (page - 1))
            puts "\n\n\ncount: #{bridge.count}\n\n\n\n"
            bridge = bridge.map{|a| a.link}
            @sorting_method = 'watched'
            #.sort{|a, b| b.visited_links.where(user: current_user).last.updated_at <=> a.visited_links.where(user: current_user).last.updated_at }
            
        when 'clip'
            bridge = current_user.clips.order(created_at: :desc).limit(limit).offset(limit * (page - 1))
            bridge = bridge.map{|a| a.link}
            @sorting_method = 'clip'
            #.sort{|a, b| b.clips.where(user: current_user).last.created_at <=> a.clips.where(user: current_user).last.created_at }
        
        when 'maum'
            bridge = current_user.likes.order(created_at: :desc).limit(limit).offset(limit * (page - 1))
            bridge = bridge.map{|a| a.link}
            @sorting_method = 'maum'
            #.sort{|a, b| b.likes.where(user: current_user).last.created_at <=> a.likes.where(user: current_user).last.created_at }
            
        end

        @links = bridge
    end
    
    

    # POST '/utils/user_watched_this_link' :: params[:user_id], params[:link_id], as: visited_link_counter
    def visited_link_counter
        vl = 'no_user' if params[:user_id] == '0'
        vl = VisitedLink.find_or_create2(params[:user_id], params[:link_id]) if params[:user_id] != '0'
        render json: vl, status: :ok
    end

    # POST '/crawler/uri_spy :: params[:url]' as: crawling_uri_path(url)
    def uri_spy

        uri = params[:url]
        @edit = false
        @edit = true if params[:edit] == 'true'

        doc = Nokogiri::HTML(open(uri, :allow_redirections => :all))
        begin
            puts doc.at("meta[property='og:title']")
        rescue ArgumentError => e
            puts "\n\n\n:::::::: ArgumentError ^^\n\n\n\n"
            doc = Nokogiri::HTML(open(uri, 'r:binary', :allow_redirections => :all).read.encode('utf-8','euc-kr'))
        end
        # puts doc.search('meta', 'title')

        title       = doc.at("meta[property='og:title']")
        puts title
        if title.nil?
            title   = doc.search('title').text.strip
        else
            begin
                title   = title['content'].encode('iso-8859-1').force_encoding('utf-8')
            rescue Encoding::UndefinedConversionError => e
                title   = title['content']
            end
        end
        puts title


        description = doc.at("meta[property='og:description']")
        if description.nil?
            description   = doc.search('description').text.strip
        else
            begin
                description   = description['content'].encode('iso-8859-1').force_encoding('utf-8')
            rescue Encoding::UndefinedConversionError => e
                description   = description['content']
            end
        end
        # puts description

        image       = doc.at("meta[property='og:image']")
        if image.nil?
            image   = doc.at("meta[name='twitter:image']")
            if image.nil?
                image   = doc.at("meta[name='weibo:webpage:image']")
                if image.nil?
                    # image   = doc.at("meta[name='naverblog:profile_image']")
                    # if image.nil?
                        image = '/svg/main_logo.svg'
                    # else
                    #     image = image['content']
                    # end
                else
                    image = image['content']
                end
            else
                image = image['content']
            end
        else
            image   = image['content']
        end
        # puts image


        url         = doc.at("meta[property='og:url']")
        if url.nil?
            url     = uri
        else
            url     = url['content']
        end
        # puts url


        description = descriptionate(description)
        image       = imaginate(image, url)
        return @target = {
            title: title,
            description: description,
            image: image,
            url: url
        }
    end
    
    def descriptionate(description)
        puts ''
        puts ''
        puts description
        puts ''
        puts ''
        if description.class.name == 'String'
            puts 'string'
            puts ''
            
            begin
                description.gsub(/(\n)/,' ')
            rescue ArgumentError => e
                # ec = Encoding::Converter.new('euc-kr', 'utf-8')
                # puts ec.convert(description)
                # puts ec.finish
                description = ''
                return description
            end
            
            d = description&.gsub(/(\n)/,' ')
            d = d&.gsub(/(\r)/,' ')
            return d
        else
            puts 'no string'
            puts ''
            return description
        end
    end
    
    def imaginate(image, url)
        split = url.split('://')
        protocol    = split[0]
        domain      = split[1].split('/').first
        return image if image == '/svg/main_logo.svg'
        image = image.first == '/' ? ( protocol + '://' + domain + image ) : image
        image
    end

    def filling_tab_group
        @tabs = []
        @tabs << { name: 'new', path: home_new_url, active: '' }
        @tabs << { name: 'my', path: home_my_url, active: '' }
    end


    # GET /letter_count
    def letter_count
        render layout: false
    end
    
    
    ###
    ### 무한 스크롤 그룹
    
    # GET /load_card/:page_num
    def load_card
        req     = params[:req]
        page    = params[:page_num].to_i || 1
        limit   = 30
        puts "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
        puts "req: #{req}"
        puts "page: #{page}"
        puts "limit: #{limit}"
        puts "\n\n"
        cards = Link.where(id: 0)
        
        if req
            puts "req: #{req.gsub('-','/')}"
            puts "method: #{params[:method]}\n\n"
            case req.gsub('-','/')
            when 'home/new_content'     # Home > New
                cards = Link.order(created_at: :desc).limit(limit).offset(limit * (page - 1))
                
            when 'home/index'           # Home > My
                cards = current_user.links.where(fandom_id: current_user.fandoms.published.ids).order(created_at: :desc).limit(limit).offset(limit * (page - 1))
            
            when 'fandoms/show'         # Planet > Library
                filter = params[:method].split('-')[0]
                sort = params[:method].split('-')[-1]
                
                case filter
                when 'default'
                    cards = Fandom.find(params[:fandom_id]).links.order(created_at: :desc).limit(limit).offset(limit * (page - 1))
                    puts 'Lib > default cards loaded'
                when 'all'
                    cards = Fandom.find(params[:fandom_id]).links.order(created_at: :desc).limit(limit).offset(limit * (page - 1))
                    puts 'Lib > all cards loaded'
                when 'image'
                    cards = Fandom.find(params[:fandom_id]).links.where(typee: 1).order(created_at: :desc).limit(limit).offset(limit * (page - 1))
                    puts 'Lib > image cards loaded'
                when 'video'
                    cards = Fandom.find(params[:fandom_id]).links.where(typee: 2).order(created_at: :desc).limit(limit).offset(limit * (page - 1))
                    puts 'Lib > video cards loaded'
                when 'others'
                    cards = Fandom.find(params[:fandom_id]).links.where(typee: [0, 3]).order(created_at: :desc).limit(limit).offset(limit * (page - 1))
                    puts 'Lib > others cards loaded'
                end
                
                case sort
                when 'default'
                    # cards = cards
                when 'Latest'
                
                when 'Popular'
                
                when 'Unwatched'
                
                when 'Clipped'
                
                end
                
            when 'mypage/watched'       # Mypage > My Links
                
                case params[:method]

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/filter_by.js.erb
var dom = '<%= escape_javascript(render partial: '/links/partials/link_card', collection: @links, as: :link) %>';

$('#libraries_wrapper').empty().append(dom)
    .attr('data-load','2')
    .attr('data-method','<%= @sorting_method %>');

$load_count = 2;
$method = '<%= @sorting_method %>';

app/views/home/index.html.erb
<style>
    #footer{ position: initial }

    .carousel .carousel-caption{
        background: none !important;
    }
</style>
<%= render partial: '/home/partials/carousel' %>

<%= render partial: '/layouts/partials/sub_nav', locals: {tabs: @tabs} %>

<%#= render partial: '/layouts/partials/toolbar' %>

<% if user_signed_in? %>
    <% if @fandoms.count.zero? %>
        <section style="text-align: center">
            <h1 class="lead_message">
                <span style="font-size: 25px; font-weight: 600;">You aren't following any Planet.</span><br>
                Follow your favorite Planets and get EVERYTHING about them!
            </h1>
            <a class="btn btn-default bgm-green btn-lg waves-effect loginFirstBtn" href="<%= fandoms_path %>">Add Following</a>
        </section>
    <% else %>
        <% if current_user.links.count.zero? %>
            <section style="text-align: center">
                <h1 class="lead_message">Save the link you want to keep<br>and Join your Channel!</h1>
            </section>
        <% else %>
            <%= render partial: '/links/partials/link_section' %>
        <% end %>
    <% end %>
<% else %>
    <section style="text-align: center">
        <h1 class="lead_message">
            Log in to HEREFAN and get the most<br>
            recent information from your followed Planets.
        </h1>
        <a class="btn btn-default bgm-blue btn-lg waves-effect loginFirstBtn" data-toggle="modal" data-target="#login_modal" style="" href="">Login</a>
    </section>
<% end %>
<style>
    .lead_message{
        margin: 70px 0 50px;
        font-size: 22px;
        font-weight: 400;
        color: #343e9d;
        line-height: 1.8;
    }
    .loginFirstBtn{
        min-width: 100px;
        height: 45px;
        background-color: #00c9c6 !important;
        font-weight: 600;
        font-size: 18px;
        color: #eee !important;
        box-shadow: none !important;
        text-transform: capitalize !important;
    }
    .loginFirstBtn:hover{
        font-weight: 700;
        color: #fff;
        border: 1px solid #CCCCCC !important;
    }
</style>

app/views/home/letter_count.html.erb
<!DOCTYPE html>
<!--[if IE 9 ]><html class="ie9"><![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Material Admin</title>

    <!-- Vendor CSS -->
    <link href="/template/vendors/bower_components/animate.css/animate.min.css" rel="stylesheet">
    <link href="/template/vendors/bower_components/bootstrap-sweetalert/lib/sweet-alert.css" rel="stylesheet">
    <link href="/template/vendors/bower_components/material-design-iconic-font/dist/css/material-design-iconic-font.min.css" rel="stylesheet">
    <link href="/template/vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" rel="stylesheet">

    <!-- CSS -->
    <link href="/template/css/app.min.1.css" rel="stylesheet">
    <link href="/template/css/app.min.2.css" rel="stylesheet">
</head>

<body>
<header id="header" class="clearfix" data-current-skin="blue">
    <ul class="header-inner">
        <li class="logo">
            <a href="index.html">이네미네 글자수 세기</a>
        </li>
    </ul>
</header>

<section id="main">
    <section id="content">
        <div class="container">
            <div class="block-header">
                <h2>글자수 카운터</h2>

                <ul class="actions">
                    <li>
                        <a class="icon-pop" href="">
                            <i class="zmdi zmdi-trending-up"></i>
                        </a>
                    </li>
                    <li>
                        <a class="icon-pop" href="">
                            <i class="zmdi zmdi-check-all"></i>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a class="icon-pop" href="" data-toggle="dropdown">
                            <i class="zmdi zmdi-more-vert"></i>
                        </a>

                        <ul class="dropdown-menu dropdown-menu-right">
                            <li>
                                <a href="">Refresh</a>
                            </li>
                            <li>
                                <a href="">Manage Widgets</a>
                            </li>
                            <li>
                                <a href="">Widgets Settings</a>
                            </li>
                        </ul>
                    </li>
                </ul>

            </div>

            <div class="card">
                <div class="card-header">
                    <!--<h2>Textarea <small>Form control which supports multiple lines of text. Change 'rows' attribute as necessary.</small></h2>-->
                </div>

                <div class="card-body card-padding">
                    <p class="c-black f-500 m-b-20">현재 글자 수</p>

                    <!--<div class="form-group">-->
                        <!--<div class="fg-line">-->
                            <!--<textarea class="form-control" rows="5" placeholder="Let us type some lorem ipsum...."></textarea>-->
                        <!--</div>-->
                    <!--</div>-->

                    <p class="c-black f-500 m-t-20 m-b-20">전체 <span id="count">0</span> 글자</p>

                    <div class="form-group">
                        <div class="fg-line">
                            <textarea id="input_textarea" class="form-control auto-size" placeholder="Start pressing Enter to see growing..."></textarea>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</section>

<footer id="footer">
    Copyright &copy; 2017 - <%= DateTime.now.year %> Fred D. Kim

    <ul class="f-menu">
        <li><a href="#">이네</a></li>
        <li><a href="#">글자수</a></li>
        <li><a href="#">잘</a></li>
        <li><a href="#">세고</a></li>
        <li><a href="#">있나요?</a></li>
    </ul>
</footer>

<!-- Page Loader -->
<div class="page-loader">
    <div class="preloader pls-blue">
        <svg class="pl-circular" viewBox="25 25 50 50">
            <circle class="plc-path" cx="50" cy="50" r="20" />
        </svg>

        <p>Please wait...</p>
    </div>
</div>

<!-- Older IE warning message -->
<!--[if lt IE 9]>
<div class="ie-warning">
    <h1 class="c-white">Warning!!</h1>
    <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>
    <div class="iew-container">
        <ul class="iew-download">
            <li>
                <a href="http://www.google.com/chrome/">
                    <img src="/template/img/browsers/chrome.png" alt="">
                    <div>Chrome</div>
                </a>
            </li>
            <li>
                <a href="https://www.mozilla.org/en-US/firefox/new/">
                    <img src="/template/img/browsers/firefox.png" alt="">
                    <div>Firefox</div>
                </a>
            </li>
            <li>
                <a href="http://www.opera.com">
                    <img src="/template/img/browsers/opera.png" alt="">
                    <div>Opera</div>
                </a>
            </li>
            <li>
                <a href="https://www.apple.com/safari/">
                    <img src="/template/img/browsers/safari.png" alt="">
                    <div>Safari</div>
                </a>
            </li>
            <li>
                <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
                    <img src="/template/img/browsers/ie.png" alt="">
                    <div>IE (New)</div>
                </a>
            </li>
        </ul>
    </div>
    <p>Sorry for the inconvenience!</p>
</div>
<![endif]-->

<!-- Javascript Libraries -->
<script src="/template/vendors/bower_components/jquery/dist/jquery.min.js"></script>
<script src="/template/vendors/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

<script src="/template/vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="/template/vendors/bower_components/Waves/dist/waves.min.js"></script>
<script src="/template/vendors/bootstrap-growl/bootstrap-growl.min.js"></script>
<script src="/template/vendors/bower_components/bootstrap-sweetalert/lib/sweet-alert.min.js"></script>
<script src="/template/vendors/bower_components/autosize/dist/autosize.min.js"></script>

<!-- Placeholder for IE9 -->
<!--[if IE 9 ]>
<script src="/template/vendors/bower_components/jquery-placeholder/jquery.placeholder.min.js"></script>
<![endif]-->

<script src="/template/js/functions.js"></script>
<script src="/template/js/demo.js"></script>

<script type="text/javascript" charset="utf-8">
    $('#input_textarea').keyup(function (event) {
        var value = $(this).val();
        var length = value.length;
        // console.log(value, length);
        $('#count').text(length);
    })
</script>

</body>
</html>

app/views/home/load_card.js.erb
////////// Start Solution

var links = [];

<% @links.each do |link| %>

    var link_dom = $("<%= escape_javascript(render '/links/partials/link_card', link: link) %>")[0];

    links.push(link_dom);

<% end %>

// console.log('links array: ', links);
// console.log('grid size: ', grid_size);

// Call prepend function in Grid-a-licious

// console.log('links array size: ', links.length);
if (links.length < 30 && links.length > 0){
    $("#libraries_wrapper").gridalicious('append', links);
    bindingActions();
    $load_count = 'end';

} else if (links.length === 0) {
    swal('Finished!', '', 'info');
    $load_count = 'end';

} else {
    $("#libraries_wrapper").gridalicious('append', links);
    bindingActions();
    $load_count = $load_count + 1;
}

////////// End Solution

app/views/home/new_content.html.erb
<style>
    #footer{ position: initial }
</style>
<%= render partial: '/home/partials/carousel' %>

<%= render partial: '/layouts/partials/sub_nav', locals: {tabs: @tabs} %>

<%#= render partial: '/layouts/partials/toolbar' %>

<%= render partial: '/links/partials/link_section' %>

app/views/home/sort_by.js.erb
var dom = '<%= escape_javascript(render partial: '/links/partials/link_card', collection: @links, as: :link) %>';

$('#libraries_wrapper').empty().append(dom)
    .attr('data-load','2')
    .attr('data-method','<%= @sorting_method %>');

$load_count = 2;
$method = '<%= @sorting_method %>';

app/views/home/uri_spy.js.erb
<% if @edit %>
var point = $('#card_preview_point-edit');
<% else %>
var point = $('#card_preview_point');
<% end %>

var dom = '<%= escape_javascript(render '/links/partials/link_card_preview', link: @target) %>';
console.log(dom);

point.empty().append(dom);

var url     = '<%== @target[:url].to_s %>';
var title   = '<%= @target[:title].to_s %>';
var desc    = '<%= @target[:description].to_s %>';
var img     = '<%== @target[:image].to_s %>';

<% if @edit %>
$('#link_urls-edit').attr('value', url);
$('#link_title-edit').attr('value', title);
$('#link_description-edit').attr('value', desc);
$('#link_image-edit').attr('value', img);
$('#reload_url_btn-edit').empty().addClass('after');
<% else %>
$('#link_urls').attr('value', url);
$('#link_title').attr('value', title);
$('#link_description').attr('value', desc);
$('#link_image').attr('value', img);
$('#reload_url_btn').empty().addClass('after');
<% end %>