config/routes.rb
Rails.application.routes.draw do
    
    resources :reports
    resources :site_masters
    scope module: :backoffice do
        get 'console/setting_planet(/:fandom_id)',  to: 'console#setting_planet'
        post 'console/save_planet_information',     to: 'console#save_planet_information'
        post 'console/save_planet_wiki',            to: 'console#save_planet_wiki'
        post 'console/add_subwiki',                 to: 'console#add_subwiki'
        get 'console/delete_subwiki/:id',           to: 'console#delete_subwiki'
        post 'console/create_wiki_info',            to: 'console#create_wiki_info'
        post 'console/update_wiki_info/:id',        to: 'console#update_wiki_info'
        post 'console/delete_wiki_info/:id',        to: 'console#delete_wiki_info'
        
        get 'console/admin'
    
        get 'console/site_config'
    
        get 'console/debug'
    end

    ## User
    devise_for :users, :controllers => {
            sessions: 'users/sessions',
            registrations: 'users/registrations',
            confirmations: 'users/confirmations',
            passwords: 'users/passwords',
            omniauth_callbacks: 'users/omniauth_callbacks'
    }
    get 'u/d', to: 'home#destroy2', as: 'user_inactivate'

    resources :myfandoms

    resources :links
    resources :fandoms do
        scope module: :planet do
            resources :wikis
            resources :histories
            resources :schedules

            resources :wiki_posts
        end
    end

    scope module: :action do
        resources :likes, path: '/action/likes'
        resources :clips, path: '/action/clips'
    end

    root 'home#go_for'
    
    # query
    # > sort by : watched, clip, maum
    get '/sort_by/:req', to: 'home#sort_by'
    
    # > load card(무한 스크롤)
    get '/load_card/:page_num', to: 'home#load_card'
    
    # > filter by : all, image, video, others
    get '/filter_by', to: 'home#filter_by'

    # home
    # > my
    get 'home/index', to: 'home#index', as: 'home_my'

    # > new
    get 'home/new', to: 'home#new_content', as: 'home_new'

    # my page
    # > my channels
    get 'mypage/my_channels', as: 'mypage_my_channels'

    # > contributed
    get 'mypage/contributed', as: 'mypage_contributed'

    # > watched
    get 'mypage/watched', as: 'mypage_watched'

    # Utility
    # > wiki post Img uploader
    post '/summernote_imageUpload', to: 'hf_util#wiki_image_uploader'
    
    # > url crawler
    post '/crawler/uri_spy', to: 'home#uri_spy', as: 'crawling_uri'

    # > link visiting counter
    post '/utils/user_watched_this_link', to: 'home#visited_link_counter', as: 'visited_link_counter'

    # > letter_counter
    get '/letter_counter', to: 'home#letter_count'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    # Admin Dashboard
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    # Error Page
    %w( 404 422 500 ).each do |code|
        get "/#{code}", to: 'errors#show', code: code
    end

    # Debug
    match 'hf_util/user_must_have_unique_myfandom/:id', to: 'hf_util#user_must_have_unique_myfandom', via: [:get]
    match 'hf_util/history/dummy/:to_do', to: 'hf_util#dummy_push', via: [:get]
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :link
  belongs_to :wiki_post
  belongs_to :history
  belongs_to :schedule
  belongs_to :fandom
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    before_action :set_report, only: [:show, :edit, :update, :destroy]
    
    # GET /reports
    # GET /reports.json
    def index
        @reports = Report.all
    end
    
    # GET /reports/1
    # GET /reports/1.json
    def show
    end
    
    # GET /reports/new
    def new
        @report = Report.new
    end
    
    # GET /reports/1/edit
    def edit
    end
    
    # POST /reports
    # POST /reports.json
    def create
        @report = Report.new(report_params)
        
        respond_to do |format|
            if @report.save
                format.html { redirect_to @report, notice: 'Report was successfully created.' }
                format.json { render :show, status: :created, location: @report }
            else
                format.html { render :new }
                format.json { render json: @report.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # PATCH/PUT /reports/1
    # PATCH/PUT /reports/1.json
    def update
        respond_to do |format|
            if @report.update(report_params)
                format.html { redirect_to @report, notice: 'Report was successfully updated.' }
                format.json { render :show, status: :ok, location: @report }
            else
                format.html { render :edit }
                format.json { render json: @report.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # DELETE /reports/1
    # DELETE /reports/1.json
    def destroy
        @report.destroy
        respond_to do |format|
            format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
            format.json { head :no_content }
        end
    end
    
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
        @report = Report.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
        params.require(:report).permit(:user_id, :link_id, :wiki_post_id, :history_id, :schedule_id, :fandom_id, :content)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= simple_form_for(@report) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :link %>
    <%= f.association :wiki_post %>
    <%= f.association :history %>
    <%= f.association :schedule %>
    <%= f.association :fandom %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Link</th>
      <th>Wiki post</th>
      <th>History</th>
      <th>Schedule</th>
      <th>Fandom</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.user %></td>
        <td><%= report.link %></td>
        <td><%= report.wiki_post %></td>
        <td><%= report.history %></td>
        <td><%= report.schedule %></td>
        <td><%= report.fandom %></td>
        <td><%= report.content %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @report.user %>
</p>

<p>
  <strong>Link:</strong>
  <%= @report.link %>
</p>

<p>
  <strong>Wiki post:</strong>
  <%= @report.wiki_post %>
</p>

<p>
  <strong>History:</strong>
  <%= @report.history %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @report.schedule %>
</p>

<p>
  <strong>Fandom:</strong>
  <%= @report.fandom %>
</p>

<p>
  <strong>Content:</strong>
  <%= @report.content %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>